#!/bin/sh
#
# Automatically adds developer name, branch name and branch description to every commit message.
#
DEVELOPER=$(git config user.name)
NAME=$(git branch | grep '*' | sed 's/* //') 
DESCRIPTION=$(git config branch."$NAME".description)

echo "$NAME"' - '$(cat "$1") > "$1"
echo "$DEVELOPER"' - '$(cat "$1") > "$1"
if [ -n "$DESCRIPTION" ] 
then
   echo "" >> "$1"
   echo $DESCRIPTION >> "$1"
fi 
